### ISSUE TITLE
Taken picture stretched only in iOS devices (Flutter web)

### ISSUE THREAD

**Issue by maherjaafar** [dint-dev/universal_html#19]
Hi.  I'm using this this method and call it. **when I take the image directly with the camera** on **portrait orientation** the image get the size of the landscape orientation but it still portrait and stretched. The problem happens just with pictures taken with the iphone camera. picture from gallery are not stretched

The method

 `pickImageWeb() async {

    html.InputElement input = html.FileUploadInputElement();

    input.type = 'file';
    input.accept = 'image/*';

    input.click();

    input.addEventListener('change', (e) {
      // read file content as dataURL
      final files = input.files;
      if (files.length == 1) {
        final file = files[0];
        html.FileReader reader = html.FileReader();

        reader.onLoadEnd.listen((e) {
          setState(() {
            uploadedImage = reader.result;
          });
        });

        reader.onError.listen((fileEvent) {
          setState(() {
            var option1Text = "Some Error occured while reading the file";
          });
        });

        reader.readAsArrayBuffer(file);
      }
    });
    html.document.body.append(input); }`
Call : 

`floatingActionButton: FloatingActionButton(
        onPressed: () => pickImageWeb(),
        child: Icon(
          Icons.add,
          color: Colors.black,
          size: 35,
        ),
      ),`

Displaying the picture : 
`Center(
          child: uploadedImage != null
              ? Image.memory(
                  uploadedImage,
                  fit: BoxFit.contain,
                )
              : Text(
                  'Body of the scaffold',
                  style: TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 40,
                  ),
                ),
        ),`

Screenshots: 
![95429221_2831129003603062_670444931776512000_n](https://user-images.githubusercontent.com/34738373/80774732-b5fd9f80-8b55-11ea-8756-3f6bc5651a40.jpg)
![95663852_244409436675795_9097332983148314624_n](https://user-images.githubusercontent.com/34738373/80774735-b7c76300-8b55-11ea-86db-d0502a43f769.jpg)

**Comment by terrier989** [comment]
Hi! The issue is unrelated to this package.
