### ISSUE TITLE
`fileUri` property of ServerSideRenderer class not used

### ISSUE THREAD

**Issue by graphicbeacon** [dint-dev/universal_html#23]
The document for the `ServerSideRenderer` suggests that I can specify a HTML file uri to use instead of the default one generated by that same class. Specifying that with the code below does not work:

```
void main() {
  final renderer = ServerSideRenderer(webAppMain, fileUri: 'web/index.html'); // <-- not working :(
  renderer.bind('localhost', 12345, onReady: (server) {});
}
```

Digging into the `ServerSideRenderer` class shows that the `fileUri` property is **not used at all**. It's just kept as a property in the class. Any workaround you can give in regards to the `fileUri`? Or am I missing anything here?

**Comment by terrier989** [comment]
This API has been deprecated in 2.0.0.
