### ISSUE TITLE
HtmlDriver does not run javascript

### ISSUE THREAD

**Issue by mymikemiller** [dint-dev/universal_html#27]
I was hoping that, as alluded to [here](https://pub.dev/packages/universal_html#browser-simulators), I could use an HtmlDriver to simulate a browser and fetch a page, running any scripts as a browser would do, and presenting me with the final rendered html.

Unfortunately, after a call to `driver.setDocumentFromUri`, `driver.document.documentElement.outerHtml` is just the html at the url I loaded, which includes script tags that were never run.

Is it possible to get HtmlDriver to run the javascript on loaded pages, and present me with the complete DOM, like I can do with JSDOM or Puppeteer in Node?

I tried using a ServerSideRenderer too, but I don't think that's right either. What am I supposed to specify for `main`? I just need it to evaluate any javascript built into the page, not my own main function.

**Comment by terrier989** [comment]
Thanks for the feedback! This sounds like something that could be solved by using [puppeteer](https://pub.dev/packages/puppeteer).
