### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by cbenhagen** [dint-dev/universal_html#30]
It would be awesome if this package could be [migrated to null safety](https://dart.dev/null-safety/migration-guide).

**Comment by jlubeck** [comment]
And the new Dart version with null-safety has been officially released today:
https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87

**Comment by devj3ns** [comment]
Hey @terrier989 do you have in the next days to migrate this package? 
It is the only dependency which has no null safety version yet in my current project. 

Would be awesome 💙

**Comment by seel-channel** [comment]
Hello. I want to migrate my package [video_viewer ](https://pub.dev/packages/video_viewer) to Null Safety, but i can't because universal_html isn't compatible with it.

**Comment by maheshmnj** [comment]
Hey I would love to submit a PR to help migrate this package to null safety.

**Comment by p0wl90** [comment]
yeah, migration to null-safety would be really appreciated!

**Comment by terrier989** [comment]
Done.

**Comment by seel-channel** [comment]
> Done.

I love you!
