### ISSUE TITLE
Getting the same build errors as 2.0.6 got on CI (but on 2.0.4 and up)

### ISSUE THREAD

**Issue by cyberpwnn** [dint-dev/universal_html#35]
Im referring to https://github.com/dint-dev/universal_html/runs/2197890452?check_suite_focus=true

Temporary workaround for latest working build is 
```yml
universal_html: 2.0.5
universal_io: 2.0.1
```

**Comment by terrier989** [comment]
Hi! Thanks for the issue report! Yes, a failure with continuous integration led to a compile-time bug in universal_io 2.0.2. Immediately becoming aware of it, universal_io 2.0.3 was released. Package universal_html now requires universal_io 2.0.3 or higher.
