### ISSUE TITLE
 latest release Universal_html: ^ 2.0.8 not working Why?

### ISSUE THREAD

**Issue by alshamynet** [dint-dev/universal_html#38]
There is no problem when I install the package .. But when I want to import it into the DART file, it does not work as if it was not installed and the red line appears under the import path.
I can only import the following path `import 'package: universal_html / web_gl.dart';`
The other paths cannot be imported.
what should I do ?

**Comment by terrier989** [comment]
Thank you for the issue report! If there was a compile-time bug, it was fixed earlier.
