### ISSUE TITLE
while create url through html.Url.createObjectUrlFromBlob(blob); throw error

### ISSUE THREAD

**Issue by laxkarparas1** [dint-dev/universal_html#43]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: UnimplementedError
E/flutter (30797): #0      Url.createObjectUrlFromBlob (package:universal_html/src/html/api/history.dart:175:5)
E/flutter (30797): #1      _MyHomePageState.decryptFile (package:flutter_screenshot/main.dart:214:21)
E/flutter (30797): <asynchronous suspension>
E/flutter (30797): #2      _MyHomePageState.perfomEncryptionTasks (package:flutter_screenshot/main.dart:147:5)
E/flutter (30797): <asynchronous suspension>
E/flutter (30797): 

i'm using this example 

final blob = html.Blob([decryptedBytes]);
     url = await html.Url.createObjectUrlFromBlob(blob);

**Comment by terrier989** [comment]
Hi! Thank you for the issue report! This package is not really meant for working with Blobs.
