### ISSUE TITLE
Update docs to reflect removal of `prefer_universal`

### ISSUE THREAD

**Issue by daniel-v** [dint-dev/universal_html#47]
0a722837bff6055af9eb04921d5b7f0e3fe99882 removed `prefer_html` and `prefer_universal` and `prefer_sdk` folders. Documentation still reflects, that these are options a developer can choose. That is misleading.

**Comment by terrier989** [comment]
Thank you for the issue report! This was fixed.

**Comment by daniel-v** [comment]
Thank you, @terrier989
