### ISSUE TITLE
Missing :nth-of-type selector

### ISSUE THREAD

**Issue by daniel-v** [dint-dev/universal_html#51]
Support for [:nth-of-type](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) css selector is currently missing.

Would be a nice enhancement - I need it :)

**Comment by daniel-v** [comment]
Started working on it here: https://github.com/daniel-v/universal_html/tree/50-nth-of-type-selector

**Comment by terrier989** [comment]
Thank you for the good issue report! 👍 This was fixed in 2.2.1.
