### ISSUE TITLE
Add possibility to get a node attribute

### ISSUE THREAD

**Issue by ppcamp** [dint-dev/universal_html#52]
First of all, congrats to you! Your package is the only one that i've found that can handle with dumbs htmls inputs (broken ones). 

Can you make the attributes of a `Node` being public? I mean, for now I'm using some regex approachs to got some attrs (like name/id/value).

```dart
// Current approach:
tree.getElementsByName('javax.faces.ViewState').first;
final jsfaces = Re.firstGroup(el.toString(), r'value=\s*"(.*)"');

// An interesting approach:
final jsfaces = tree.getElementsByName('javax.faces.ViewState').first.attributes['value'];
```

**Comment by terrier989** [comment]
Thank you for the positive feedback! You could solve the issue by doing `node as Element` cast.
