### ISSUE TITLE
window.location.pathname returns String instead of String?

### ISSUE THREAD

**Issue by minhqdao** [dint-dev/universal_html#56]
`window.location.pathname` is supposed to return a `String?`, which is why you would typically use it as:

`final isHome = window.location.pathname?.contains('home') ?? false;`

If you do that, however, you will receive the following warning under macOS:

`: Warning: Operand of null-aware operation '?.' has type 'String' which excludes null.`

Seems like somewhere a `String` is returned, while a `String?` would be more appropriate. 🤔

**Comment by radvansky-tomas** [comment]
There is same issue for `window.location.origin`
