### ISSUE TITLE
"Null check operator used on a null value" when passing empty string to querySelectorAll("")

### ISSUE THREAD

**Issue by Aulig** [dint-dev/universal_html#64]
The null check `css.parseSelectorGroup(input)!` in `querySelectorAll<T extends Element>(String input)` in `node.dart` throws an exception if you pass an empty string as input.

Same issue occurs with `querySelector`, as that also calls `querySelectorAll`.

Expected result would be returning an empty list or a clearer exception.

**Comment by terrier989** [comment]
Thank you for the issue report! This was fixed in 2.1.0.
