### ISSUE TITLE
Different behaviour in `dart:js` and `package:universal_html/js.dart`

### ISSUE THREAD

**Issue by MatthaiosSait** [dint-dev/universal_html#67]
In https://github.com/dint-dev/universal_html/blob/0ea6592b88b0814edfce0ff10cb9a7159f87f9a6/lib/src/js.dart#L214
the `Object` is not nullable, whereas in 

https://github.com/dart-lang/sdk/blob/234128e8d37d78f4c03405734eba3b05a6691ce5/sdk/lib/js/js.dart#L131

the value is nullable.

As an example, we cannot set the context with this operator, e.g.     `context['define'] = null;`

**Comment by terrier989** [comment]
Thank you for the issue report! This was fixed in 2.1.0.
