### ISSUE TITLE
please add flutter 3.10 full support and update package on pub

### ISSUE THREAD

**Issue by fisforfaheem** [dint-dev/universal_html#72]
its causing issues like dart2js

**Comment by terrier989** [comment]
Thank you for the issue report! This is now done.

**Comment by fisforfaheem** [comment]
Can you also update these as well ( I have updated them) 
 async: ^2.11.0
  csslib: ^0.17.2
  charcode: ^1.3.1
  collection: ^1.17.2
  html: ^0.15.3
  meta: ^1.9.1
  source_span: ^1.10.0
  typed_data: ^1.3.2
  universal_io: ^2.2.1



I have made a fork and also contributed please see and update.

**Comment by EchoEllet** [comment]
> Can you also update these as well ( I have updated them)
> async: ^2.11.0
> csslib: ^0.17.2
> charcode: ^1.3.1
> collection: ^1.17.2
> html: ^0.15.3
> meta: ^1.9.1
> source_span: ^1.10.0
> typed_data: ^1.3.2
> universal_io: ^2.2.1

The package doesn't need to update them, the `pubspec.yaml` defines the minimum required versions for dependencies, when the client runs `flutter pub get` they will get the latest version which is stored in `pubspec.lock` and can upgrade with `flutter pub upgrade`. It's not a good practice for packages especially published on pub.dev to force updating the dependencies unless they require a feature or a breaking release introduced.

For app packages, you can update them manually in `flutter pub upgrade` or `flutter pub upgrade --major-versions` which will only bump to their latest major release. Still, it's also not necessary to update the dependencies manually in `pubspec.yaml` but it's ok to do.

See the following resources:

* https://dart.dev/tools/pub/dependencies#version-constraints
* https://docs.flutter.dev/packages-and-plugins/using-packages#conflict-resolution
