### ISSUE TITLE
universal_html-2.2.2/lib/src/html/dom/element_subclasses.dart:2752:30: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.  - 'Object' is from 'dart:core'.

### ISSUE THREAD

**Issue by danuprakoso26** [dint-dev/universal_html#76]
this happens on universal html v2.2.2 and flutter sdk 3.10.0. I tried to downgrade to 3.7.12 but still the same.

![image](https://github.com/dint-dev/universal_html/assets/49750047/86ebc58a-d773-4ae6-bbbc-ae1e3219cca4)

**Comment by 4dcity** [comment]
My flutter version is 3.7.7，I got the same error
it worked fine yesterday，have no idea what change casued this error...

**Comment by raghavsatyadev** [comment]
@danuprakoso26 @4dcity include this dependency in your pubspec.yaml. Yesterday a new version was released for this lib and it broke universal_html. This will limit the csslib to be of old version instead of always updating whenever there is a new version

csslib: 0.17.0

**Comment by danuprakoso26** [comment]
> @danuprakoso26 @4dcity include this dependency in your pubspec.yaml. Yesterday a new version was released for this lib and it broke universal_html. This will limit the csslib to be of old version instead of always updating whenever there is a new version
> 
> `csslib: 0.17.0`

did you mean remove the ^ sign? I did it from v3.0.5 to v2.2.2. none of them work

**Comment by danuprakoso26** [comment]
> > @danuprakoso26 @4dcity include this dependency in your pubspec.yaml. Yesterday a new version was released for this lib and it broke universal_html. This will limit the csslib to be of old version instead of always updating whenever there is a new version
> > `csslib: 0.17.0`
> 
oh wow. what a life saver. thank you

**Comment by 4dcity** [comment]
@raghavsatyadev problem solved！thanks a lot！
hope the project maintainer can fix this in a newer version

**Comment by ashish-d-hh** [comment]
Thanks

**Comment by mrcsh** [comment]
@raghavsatyadev Ugh, I spent hours yesterday trying to figure out why my release branch would not build but my dev branch would.  I would have eventually found it but many thanks for the short cut.

**Comment by sarthak-grappus** [comment]
we arent even using it  and  getting the error and that too at client side 😤

**Comment by VenkataRaoRayala** [comment]
Hi all, just downloaded this plugin code,  at [universal_html-2.2.2/lib/src/html/dom/element_subclasses.dart:2752] you missed to add ! to text object. I am using flutter 3.1.0. Error got resolved. 

change this 
    final parsed = css.parse(text);  
to this 
    final parsed = css.parse(text!);

Please publish this change, it will help us a lot!!!!

**Comment by Octavian25** [comment]
> 

Thank you very much, this change has been extremely helpful and works well. I kindly request the developers to publish these changes.

**Comment by Octavian25** [comment]
> Hi all, just downloaded this plugin code, at [universal_html-2.2.2/lib/src/html/dom/element_subclasses.dart:2752] you missed to add ! to text object. I am using flutter 3.1.0. Error got resolved.
> 
> change this final parsed = css.parse(text); to this final parsed = css.parse(text!);
> 
> and also please update all the packages to latest in pubpect.yaml file
> 
> Please publish this change, it will help us a lot!!!!


Thank you very much, this change has been extremely helpful and works well. I kindly request the developers to publish these changes.

**Comment by RoyalCoder88** [comment]
Please fix this issue, have the same issue :(

```
Launching lib\main.dart on SM A908B in debug mode...
../../../AppData/Local/Pub/Cache/hosted/pub.dev/universal_html-2.2.2/lib/src/html/dom/element_subclasses.dart:2752:30: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
    final parsed = css.parse(text);
                             ^
Target kernel_snapshot failed: Exception

> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Running Gradle task 'assembleDebug'...                             38.8s
Exception: Gradle task assembleDebug failed with exit code 1
```

Thanks in advance!

**Comment by Mike-3** [comment]
I have the same exception.

**Comment by samumzizi** [comment]
> 

Yes, this is what I did too (adding the exclamation mark) and it worked.

**Comment by rymesaint** [comment]
i have the same problem after upgraded the flutter

**Comment by andre-morpanini-maersk** [comment]
I have the same problem here

**Comment by Morpa** [comment]
Here the same problem is happening. Even updating to the latest version. 
I saw that the csslib is already with the version 0.17.3

**Comment by brux88** [comment]
i have the same problem

**Comment by iameerhamza** [comment]
> @danuprakoso26 @4dcity include this dependency in your pubspec.yaml. Yesterday a new version was released for this lib and it broke universal_html. This will limit the csslib to be of old version instead of always updating whenever there is a new version
> 
> `csslib: 0.17.0`

it didnt work while building app for ios

**Comment by raghavsatyadev** [comment]
> > @danuprakoso26 @4dcity include this dependency in your pubspec.yaml. Yesterday a new version was released for this lib and it broke universal_html. This will limit the csslib to be of old version instead of always updating whenever there is a new version
> > `csslib: 0.17.0`
> 
> it didnt work while building app for ios

May be some other dependency is causing the issue on your side as we have successfully made the builds and pushed

**Comment by mftlhn** [comment]
> Hi all, just downloaded this plugin code, at [universal_html-2.2.2/lib/src/html/dom/element_subclasses.dart:2752] you missed to add ! to text object. I am using flutter 3.1.0. Error got resolved.
> 
> change this final parsed = css.parse(text); to this final parsed = css.parse(text!);
> 
> and also please update all the packages to latest in pubpect.yaml file
> 
> Please publish this change, it will help us a lot!!!!

thanks. it's extremely helpful

**Comment by ErnestGaisieViuHealth** [comment]
> @danuprakoso26 @4dcity include this dependency in your pubspec.yaml. Yesterday a new version was released for this lib and it broke universal_html. This will limit the csslib to be of old version instead of always updating whenever there is a new version
> 
> `csslib: 0.17.0`

Thanks soo much. I've been facing this issue for days. Thumbs up 👍

**Comment by shanaka-sync** [comment]
> The fix for me was:
> 
> ```
> dependency_overrides:
>   csslib: 0.17.0
>   universal_html: 2.0.8
> ```
> 
> I do not use `csslib`, but the override is needed.
> 
> The 2.0.8 verson number I got from searching for "universal_html" in all pubspec.yaml from the folder `c:\Users\<username>\AppData\Local\Pub\Cache\hosted\pub.dev\`
> 
> There was a single result `c:\Users\<username>\AppData\Local\Pub\Cache\hosted\pub.dev\flick_video_player-0.5.0\pubspec.yaml` using `universal_html: ^2.0.8`

Thankx dude, This works for me.
