### ISSUE TITLE
The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.

### ISSUE THREAD

**Issue by lexoops** [dint-dev/universal_html#79]
<img width="1345" alt="image" src="https://github.com/dint-dev/universal_html/assets/33716494/dea1e84b-4420-4f8a-a757-aef08f1586f5">
<img width="613" alt="image" src="https://github.com/dint-dev/universal_html/assets/33716494/a6e8bb62-d85b-4318-ab5c-7bb9d127fe28">

Error (Xcode): ../../.pub-cache/hosted/pub.flutter-io.cn/universal_html-2.0.8/lib/src/html/dom/element_subclasses.dart:2711:30: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.

please help, on mac os, i can not build ios app.

**Comment by naseeem** [comment]
@lexoops see this https://github.com/dint-dev/universal_html/issues/76#issuecomment-1558621694

**Comment by dhruvil444** [comment]
Add this dependency in your pubspec.yaml 👇🏻
csslib: 0.17.0

**Comment by Haris2v** [comment]
Thank you @dhruvil444 your solution saved my day!

**Comment by nishat-nasir** [comment]
**Thank you @dhruvil444 ,** I have spent 5 hours before I found your solution

**Comment by rickynguyenc** [comment]
> Add this dependency in your pubspec.yaml 👇🏻 csslib: 0.17.0

Thanks you so much
